""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" FILENAME: gvimrc
" AUTHOR: James Shackleford
" UPDATED: 07.10.2015
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" disable toolbar
set guioptions-=T

" enable mouse
set mouse=a

" let's be easy on the eyes
colorscheme slate

" the standard 80 + line numbers
set columns=90

" make vim usefully tall
set lines=50
