""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" FILENAME: gvimrc
" AUTHOR: James Shackleford
" UPDATED: 07.10.2015
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

colorscheme slate

" disable toolbar
set guioptions-=T

" 90x50 gvim sessions
set columns=90
set lines=50
